Workdir
shudv2021/TestGuru pull request #1
Opened 2021-07-07 18:55 UTC by shudv2021

I add several statik pages 
I add time zone and preference language

2021-07-08 07:28 UTC, BubuntuClu requested changes

2021-07-08 07:28 UTC, BubuntuClu commented on .idea/.gitignore
> +# Default ignored files
все твои файлы настроек должны быть прописаны в файле gitignor. у каждого разработчика свои настройки и ему твои не нужны)

2021-07-08 07:28 UTC, BubuntuClu commented on app/controllers/info_pages_controller.rb
> +class InfoPagesController < ApplicationController
делаем без контроллера, это статические страницы

2021-07-08 07:28 UTC, BubuntuClu commented on config/routes.rb
> +  get '/about', to: 'info_pages#about'
без роута. папка паблик не нуждается в роутах и контроллерах

2021-07-08 07:28 UTC, BubuntuClu commented on public/author.html
> +<p>по ссылке <a>https://github.com/shudv2021/TestGuru</a></p>
ссылки на сторонние ресурсы нужно откарывать в новой вкладке

2021-07-08 07:28 UTC, BubuntuClu commented on app/views/info_pages/about.html.erb
> +<h1>InfoPages#about</h1>
эта страница тоже должна быть в паблик папке

2021-07-08 07:28 UTC, BubuntuClu commented on app/views/info_pages/about.html.erb
> +<p>Делается по заданию  <a>www.thinknetica.com</a></p>
ссылки на сторонние ресурсы нужно откарывать в новой вкладке

2021-07-08 18:14 UTC, BubuntuClu requested changes

2021-07-08 18:14 UTC, BubuntuClu commented on config/initializers/version.rb
> +VERSION = %w[1 0 1]
1 - сейчас это глобальная константа, что не очень хорошо. измени тут код так, чтобы можно было получить версию приложения через код `TestGuru.version`
2 - стартовые цифры версии другие

2021-07-08 18:14 UTC, BubuntuClu commented on config/routes.rb
> +  #get '/about', to: 'info_pages#about'
можешь удалить этот код, он все равно не потруется, да и зассорять комментариями код не очень красиов

2021-07-08 18:14 UTC, BubuntuClu commented on d
> +[33mcommit 95ee103497c7f5d97ed5ccc9339534336509ae46[m[33m ([m[1;36mHEAD -> [m[1;32mworkdir[m[33m, [m[1;31morigin/workdir[m[33m)[m
можешь удалить файл

2021-07-08 18:14 UTC, BubuntuClu commented on public/about.html
> +<a href = "www.thinknetica.com">www.thinknetica.com</a>
ссылки на сторонние ресурсы открываем в новой вкладке

2021-07-08 18:14 UTC, BubuntuClu commented on public/author.html
> +<a href = "https://github.com/shudv2021/TestGuru">https://github.com/shudv2021/TestGuru</a>
ссылки на сторонние ресурсы открываем в новой вкладке

2021-07-09 07:51 UTC, shudv2021 commented on .idea/.gitignore
> +# Default ignored files
исправлено

2021-07-09 07:51 UTC, shudv2021 commented on app/controllers/info_pages_controller.rb
> +class InfoPagesController < ApplicationController
исправлено

2021-07-09 07:51 UTC, shudv2021 commented on config/routes.rb
> +  get '/about', to: 'info_pages#about'
Исправлено

2021-07-09 07:52 UTC, shudv2021 commented on public/author.html
> +<p>по ссылке <a>https://github.com/shudv2021/TestGuru</a></p>
Исправлено

2021-07-09 07:52 UTC, shudv2021 commented on app/views/info_pages/about.html.erb
> +<h1>InfoPages#about</h1>
Исправлено

2021-07-09 07:52 UTC, shudv2021 commented on app/views/info_pages/about.html.erb
> +<p>Делается по заданию  <a>www.thinknetica.com</a></p>
Исправлено

2021-07-09 07:52 UTC, shudv2021 commented on config/initializers/version.rb
> +VERSION = %w[1 0 1]
Возможо исправлено

2021-07-09 07:53 UTC, shudv2021 commented on config/routes.rb
> +  #get '/about', to: 'info_pages#about'
Исправлено

2021-07-09 07:53 UTC, shudv2021 commented on public/about.html
> +<a href = "www.thinknetica.com">www.thinknetica.com</a>
Исправлено

2021-07-09 07:53 UTC, shudv2021 commented on public/author.html
> +<a href = "https://github.com/shudv2021/TestGuru">https://github.com/shudv2021/TestGuru</a>
Исправлено

2021-07-09 17:52 UTC, BubuntuClu approved these changes

2021-07-09 17:52 UTC, BubuntuClu commented on .gitignore
> +d
зачем его помещать в гитигнор? просто удали и все

2021-07-09 17:52 UTC, BubuntuClu commented on config/application.rb
> +
лишние пустые строки

2021-07-09 17:52 UTC, BubuntuClu commented on config/initializers/version.rb
> +    version = '0.1.0'
зачем переменная? ты же никаких манипуляций не делаешь, возвращай просто строку

2021-07-09 17:52 UTC, BubuntuClu commented on config/initializers/version.rb
> +    end
отступ уехал

2021-07-09 17:52 UTC, BubuntuClu commented on config/initializers/version.rb
> +end
В IDE сделай настройку, чтобы добавлялась пустая строка в конец файла. Это исправит ворнинг на гитхабе

2021-07-09 17:52 UTC, BubuntuClu commented on nano.save
> +^^
тоже лишний какой-то файл, надо удалить

2021-07-16 06:31 UTC, merged