lesson10 attempt1
shudv2021/TestGuru pull request #10
Opened 2021-08-11 05:35 UTC by shudv2021

first push

2021-08-11 18:23 UTC, BubuntuClu requested changes

2021-08-11 18:23 UTC, BubuntuClu commented on config/routes.rb
> +  get 'sessions/new'
надо убрать дубли путей
2-4 строки надо удалить

2021-08-11 18:23 UTC, BubuntuClu commented on db/migrate/20210714072245_create_users.rb
> +      t.string :password_digest
так делать нельзя. править миграции задним числом не допустимо, так как твои изменения не будут применены у других разрабочтиков.

откати тут это изменений и добавь миграцию на переименовывание поля

2021-08-11 18:23 UTC, BubuntuClu commented on db/migrate/20210810111658_remove_passvord_from_users.rb
> +  def up
если есть `up`, то должен быть и `down`, чтобы не было ошибки при откате миграции

2021-08-11 18:23 UTC, BubuntuClu commented on db/migrate/20210810111658_remove_passvord_from_users.rb
> +    remove_column :users, :password, :string
какая-то странная последовательность действий, сначала ты переименовал поле в миграции создания таблицы, потом удаляешь это поле и ниже добавляешь новое. убери все ненужные этапы, оставь один способ

2021-08-11 18:25 UTC, BubuntuClu requested changes

2021-08-11 18:25 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      render new
не валидный руби код

2021-08-11 18:25 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, presence: true, uniqueness: true
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный индекс надо

2021-08-13 07:36 UTC, BubuntuClu requested changes

2021-08-13 07:36 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
>    before_action :find_test, only: %i[ edit update destroy show start]
тут старт надо удалить

2021-08-13 07:36 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      redirect_to "#{cookies[:path]}"
почему кука с интерполяцией?
`path`? что за путь?

`redirect_to cookies[:good_name] || root_path`

2021-08-13 07:36 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    cookies[:path] = "/#{params[:controller]}/#{params[:action]}"
из объекта `request` доставай путь, твой способ потеряет параметры, которые могуть быть в пути.
так же созхраниять стоит только если пользователь не авторизован

2021-08-13 07:36 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, presence: true, uniqueness: true, format: {with: /.+@.+\..+/i}
`with: URI::MailTo::EMAIL_REGEXP`
 и перечитай еще раз коммент про дублирование ограничения. не вижу индекса в БД

2021-08-13 15:30 UTC, shudv2021 commented on app/controllers/tests_controller.rb
>    before_action :find_test, only: %i[ edit update destroy show start]
исправлено

2021-08-14 16:46 UTC, merged