add migratin from hw3 first attempt
shudv2021/TestGuru pull request #2
Opened 2021-07-14 10:55 UTC by shudv2021

2021-07-14 18:05 UTC, BubuntuClu requested changes

2021-07-14 18:05 UTC, BubuntuClu commented on db/migrate/20210714073436_create_categories.rb
> +      t.string :category_title
просто `title`, и так понятно что оно для категории

2021-07-14 18:05 UTC, BubuntuClu commented on db/migrate/20210714070910_create_questions.rb
> +      t.integer :test_id
кроме того что это столбец, тут должен быть еще индекс и внешний ключ. посмотри в сторону `t.refences :test, foreign_key: true`

2021-07-14 18:05 UTC, BubuntuClu commented on db/migrate/20210714071701_create_answers.rb
> +      t.integer :question_id
везде где идет связь с другой таблицей надо указать индекс и внешний ключ

2021-07-15 07:21 UTC, shudv2021 commented on db/migrate/20210714073436_create_categories.rb
> +      t.string :category_title
исправлено

2021-07-15 07:22 UTC, shudv2021 commented on db/migrate/20210714070910_create_questions.rb
> +      t.integer :test_id
Исправлено

2021-07-15 07:22 UTC, shudv2021 commented on db/migrate/20210714071701_create_answers.rb
> +      t.integer :question_id
Исправлено

2021-07-15 17:30 UTC, BubuntuClu requested changes

2021-07-15 17:30 UTC, BubuntuClu commented on db/migrate/20210714072245_create_users.rb
> +      t.references :test, foreign_key: true
а где сама миграция таблицы тестов? в schema.rb есть ее добавление, но миграции нет. так же в тестах нет связи с категорией

2021-07-15 17:30 UTC, BubuntuClu commented on db/migrate/20210714072245_create_users.rb
> +      t.references :test, foreign_key: true
пользователя с тестом хочешь связать с какой целью?

2021-07-16 06:16 UTC, BubuntuClu commented on db/migrate/20210711120613_create_tests.rb
> +      t.references :categorie, foriegn_key: true
:category будет правильное имя в единственном числе

>Про то что миграции нет не понял.
видишь, у тебя эта миграция не в ПРе, только когда ты добавил сюда новую строку она отображается в изменении. где ты создал эту миграцию? почему ее нет в этом ПРе?

2021-07-16 06:16 UTC, BubuntuClu commented on db/migrate/20210714072245_create_users.rb
> +      t.references :test, foreign_key: true
>Пользователю хочу добавлять тест с которым он работал в последний раз.
что значит последний раз работал? как это будет выглядеть?

2021-07-16 12:40 UTC, BubuntuClu commented on db/migrate/20210713104621_create_tests.rb
> +      t.references :categoriy, foriegn_key: true
`:category`

2021-07-16 12:40 UTC, BubuntuClu commented on db/migrate/20210714070910_create_questions.rb
> +      t.references :test, foriegn_key: true
`:foreign_key`
везде где опечатка надо поменять

2021-07-16 12:40 UTC, BubuntuClu commented on db/migrate/20210714074500_add_tests_null_constraing.rb
> +    change_column_null(:tests, :categoriy_id, false)
тут ключ categoriy_id надо будет поменять

2021-07-16 14:39 UTC, merged