add timer
shudv2021/TestGuru pull request #20
Opened 2021-11-21 16:28 UTC by shudv2021

2021-11-21 17:41 UTC, BubuntuClu requested changes

2021-11-21 17:41 UTC, BubuntuClu commented on db/migrate/20211120103337_add_time_limit_to_test.rb
> +    add_column :tests, :time_limit, :integer, null: false, default: 1
дефолтное значение не стоит задавать. или 0, с обработкой того что 0 это будто нет таймера

2021-11-21 17:41 UTC, BubuntuClu commented on app/views/test_passages/show.html.erb
> +           data: { remaining_time: @test_passage.test.time_limit*60 } do %>
а зачем тут `do/end`?

2021-11-23 06:50 UTC, BubuntuClu requested changes

2021-11-23 06:50 UTC, BubuntuClu commented on db/migrate/20211120103337_add_time_limit_to_test.rb
> +    add_column :tests, :time_limit, :integer, null: false, default: 1
это надо поправить

2021-11-23 13:11 UTC, BubuntuClu commented on db/migrate/20211120103337_add_time_limit_to_test.rb
> +    add_column :tests, :time_limit, :integer, null: false, default: 0
ты просто изменил тут цифру, но надо было сделать ролбэк и потом изменить.
строка `t.integer "time_limit", default: 1, null: false` из `schema.rb` тебя выдает

2021-11-23 13:12 UTC, BubuntuClu commented on app/javascript/packs/application.js
> -import './utilites/timer'
это надо вернуть. на фронте таймер должен тикать

2021-11-23 13:48 UTC, BubuntuClu commented on db/migrate/20211123130728_create_bage.rb
> +      t.bulean :usage
ошибка

2021-11-23 13:49 UTC, BubuntuClu commented on db/migrate/20211123130728_create_bage.rb
> +      t.bulean :usage
и за что будет отвечать это поле?

2021-11-23 13:49 UTC, BubuntuClu commented on db/migrate/20211123130756_create_user_bage.rb
> +      t.references :bage, null: false, foreign_key: true
вроде правильное слово `badge`

2021-11-23 17:52 UTC, shudv2021 commented on db/migrate/20211123130728_create_bage.rb
> +      t.bulean :usage
Это из следующей ветки попало -ошибка, исправил . Boolean поле будет отвечать подключен данный бэйдж или нет

2021-11-24 18:40 UTC, merged