Seed two methods
shudv2021/TestGuru pull request #4
Opened 2021-07-17 11:41 UTC by shudv2021

fill file seed.rb
add method by_category
will made method all_tests for User

2021-07-17 17:49 UTC, BubuntuClu requested changes

2021-07-17 17:49 UTC, BubuntuClu commented on app/models/test.rb
> +    #  Test.joins('JOIN categories ON tests.category_id = categories.id').where("category = :category", category:category)
вот это правильный запрос, он за один раз назодит нужные тесты, а не через два запроса к БД. надо добавить соритровку.

2021-07-17 17:49 UTC, BubuntuClu commented on app/models/test.rb
> +    pp Test.where(category_id: category_id).order!('id DESC')
почему `order!`?

2021-07-17 17:49 UTC, BubuntuClu commented on db/seeds.rb
> +   {title:'Ruby', level:1, category_id:2},
хардкодить id нельзя. созданные категории сохрани в объект и используй их при создании тестов. так же сохраняй тесты и тд

2021-07-18 18:23 UTC, BubuntuClu requested changes

2021-07-18 18:23 UTC, BubuntuClu commented on app/models/test.rb
> +end
в IDE сделай настройку чтобы добавлялась пустая строка в конце файла, чтобы убрать этот ворнинг

2021-07-18 18:23 UTC, BubuntuClu commented on app/models/user.rb
> +    TestAction.joins('JOIN tests ON test_actions.test_id = tests.id')
тебе нужно получить тесты, а не строки из промежуточной таблицы

2021-07-18 18:23 UTC, BubuntuClu commented on db/seeds.rb
> +   {title:'Ruby', level:2, category_id:2},
тут не поменялось ничего

2021-07-18 18:23 UTC, BubuntuClu commented on app/models/test.rb
> +           .order('id DESC')
нужно указать из какой таблицы поле id участвует в сортировке

2021-07-19 05:16 UTC, shudv2021 commented on app/models/user.rb
> +    TestAction.joins('JOIN tests ON test_actions.test_id = tests.id')
исправил

2021-07-19 05:17 UTC, shudv2021 commented on app/models/test.rb
> +end
Поставил. А что за ворнинг и где ты видишь его?

2021-07-19 05:31 UTC, shudv2021 commented on db/seeds.rb
> +   {title:'Ruby', level:2, category_id:2},
А что тут должно поменяться?  
 {test_id:1, body:'For what Ruby is used usually'},
  {test_id:3, body:'For what HTML is used'},
почему задес допустимо  здесь тоже записан id в качестве внешнего ключа. 
"хардкодить id нельзя. созданные категории сохрани в объект и используй их при создании тестов. так же сохраняй тесты и тд" - фраза абсолютно непонятна.

2021-07-19 07:27 UTC, BubuntuClu commented on app/models/test.rb
> +end
красная черта в круге, при просмотре файлов ее видно

2021-07-19 07:32 UTC, BubuntuClu commented on db/seeds.rb
> +   {title:'Ruby', level:2, category_id:2},
>хардкодить id нельзя.

вот у тебя есть один из элементов массива для создания теста `{title:'Ruby', level:1, category_id:2},`, тут есть такая запись `category_id:2`, ты жестко привязываешь этот тест к категории с id 2. если у тебя не будет категории стаким id, то тест не будет создан. то что ты выше создаешь несколько категорий, не гарантирует тебе что у них id всегда будут начинаться с 1. в разных БД последовательность отвечающая за id имеет разный алгоритм. прогнав несколько раз сид, у тебя id улетит вперед, и сид начнет работать криво

`почему задес допустимо здесь тоже записан id в качестве внешнего ключа.` - не допустимо, я просто оставил комментарий на другой строке, чтобы он был не в истории выше, а появился в новом сете комменатриев.

`созданные категории сохрани в объект и используй их при создании тестов` - чтобы решить проблему с харкдоком id при создании зависимых объектов, у тебя есть возможность использовать одну из фич ООП- объекты. сохранив категории, при их создании, ты будешь имееть объекты у которых ты можешь взять id и он
железобетенно будет в БД, так как ты только что его создал с этими данными, и БД вернула id для него.

такую операцию надо провернуть со всеми объектами, которые ты создаешь, с привязкой к другой таблице по внешнему ключа

2021-07-19 12:13 UTC, shudv2021 commented on db/seeds.rb
> +   {title:'Ruby', level:1, category_id:2},
Исправил

2021-07-20 14:53 UTC, merged