Lesson8
shudv2021/TestGuru pull request #8
Opened 2021-08-01 15:19 UTC by shudv2021

2021-08-01 17:51 UTC, BubuntuClu requested changes

2021-08-01 17:51 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    byebug
это надо убирать из ПРов

2021-08-01 17:51 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  def index
этот метод уже не нужен. список вопросов выводится на странице теста

2021-08-01 17:51 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    render html: "<p>#{@question.body}</p>".html_safe
выводить надо уже вьюхи, а не свой текст

2021-08-01 17:51 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +      render html: "<p>Question saved</p>".html_safe
редирект должен быть на страницу созданного теста

2021-08-01 17:51 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +      render html: "<p>Saving failed</p>".html_safe
отрисовать надо вьюху :new

2021-08-01 17:51 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +      render html: "<p>Question del</p>".html_safe
редирект на страницу теста

2021-08-01 17:51 UTC, BubuntuClu commented on config/routes.rb
> +  get '/questions/:id/del', to: 'questions#destroy'
ты это можешь тестировать локально, но в ПРе этого не должно быть

2021-08-01 17:51 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = Test.new(test_params)
`belongs_to :author, class_name: 'User', foreign_key: 'user_id'`
автора требуется указать чтобы создать тест. если вызовешь `@test.save!` тебе будет ошибка про это

2021-08-03 06:47 UTC, BubuntuClu requested changes

2021-08-03 06:47 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    #question = "<p>#{question.body}</p>"
удаляй сразу все комментарии, они загрзяняют код. если потребуется подсмотреть, то ты используешь гит и можешь смотреть старые версии файла

2021-08-03 06:47 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = Test.find(params[:id])
этот метод дублируется

2021-08-03 06:47 UTC, BubuntuClu commented on db/migrate/20210802031931_add_test_default_creator.rb
> +      change_column_default(:tests, :user_id, 4)
так делать нельзя. как минимум ты хардкодишь ID которого может не быть.
через консоль тестам проставь у кого нет проставлено, через миграцию это не надо делать.
а добавь автора в код создания теста

2021-08-04 04:02 UTC, shudv2021 commented on app/controllers/questions_controller.rb
> +    #question = "<p>#{question.body}</p>"
удалил

2021-08-04 06:58 UTC, BubuntuClu requested changes

2021-08-04 06:58 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +      redirect_to(@test)
потому что у тебя не найден этот объект. в колбэке ты его не ищешь, значит он будет пустой, логично?)
зато тут у тебя есть объект вопроса
`redirect_to(@question.test)`

2021-08-04 06:58 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +    Time.now
по заданию нужен год

2021-08-04 06:58 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +    Test.find(params[:id]).title
это что такое? почему ты пытаешься каждый раз найти объект? ты в контроллере нашел тест, он у тебя доступен пока ответ не отдался клиенту.
но все равно это неправильно.
передавай сюда объект вопроса и у него используй метод `new_record?persisted?`чтобы определить какой заголовок отдать надо

2021-08-04 08:16 UTC, shudv2021 commented on app/controllers/tests_controller.rb
> +    byebug
убрал

2021-08-04 08:17 UTC, shudv2021 commented on app/controllers/tests_controller.rb
> +    byebug
убрал

2021-08-04 08:17 UTC, shudv2021 commented on app/controllers/questions_controller.rb
> +  def index
убрал index

2021-08-04 08:54 UTC, shudv2021 commented on app/helpers/application_helper.rb
> +    Time.now
исправил

2021-08-04 15:28 UTC, shudv2021 commented on app/controllers/tests_controller.rb
> +    @test = Test.new(test_params)
добавил авторство в форму

2021-08-04 17:22 UTC, BubuntuClu requested changes

2021-08-04 17:22 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question=Question.find(params[:id])
у тебя есть вот такое поведение в контроллере
```
before_action :find_question, only: %i[show destroy]
 def find_question
    @question = Question.find(params[:id])
  end
```

зачем тут строка 
`@question=Question.find(params[:id])`?

2021-08-04 17:22 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
дублирование кода, смотри колбэк и метод find_question

2021-08-04 17:22 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
дублирование кода, смотри колбэк и метод find_question

2021-08-04 17:22 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +    question.test.title
>Это должен быть один метод question_header который в форме создания вопроса будет выводить Create New <Test Title> Question, а в форме редактирования Edit <Test Title> Question

у тебя сейчас выводиться только заголовок теста, а надо еще другие слова добавить. без них в методе нет смысла

2021-08-04 17:22 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<h1> Edit <%=question_header(@question)%> Question </h1>
чтобы тут не писать EDIT ... QUESTION, ты и используешь метод. чтобы просто разместив метод на форме он сам выдал нужный текст.

2021-08-04 17:22 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<h1>  Create new <%=question_header(@question)%> Question </h1>
чтобы тут не писать EDIT ... QUESTION, ты и используешь метод. чтобы просто разместив метод на форме он сам выдал нужный текст.

2021-08-04 17:22 UTC, BubuntuClu commented on app/views/tests/_form.html.erb
>      <%= form.collection_select :category_id, Category.all, :id, :title, prompt: true%>
в этой форме должен ставиться заголовок страницы, в одном месте вызываешь метод, он уже по состоянию вопроса смотрит какой текст отдать

2021-08-05 03:28 UTC, shudv2021 commented on app/controllers/questions_controller.rb
> +    @question=Question.find(params[:id])
убрал строки дублирующие метод find_question

2021-08-05 03:29 UTC, shudv2021 commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
убрал строки дублирующие метод find_question

2021-08-05 03:29 UTC, shudv2021 commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
убрал строки дублирующие метод find_question

2021-08-05 03:29 UTC, shudv2021 commented on app/helpers/questions_helper.rb
> +    question.test.title
Переделала метод

2021-08-05 03:29 UTC, shudv2021 commented on app/views/questions/edit.html.erb
> +<h1> Edit <%=question_header(@question)%> Question </h1>
Переделала метод

2021-08-05 03:30 UTC, shudv2021 commented on app/views/tests/_form.html.erb
>      <%= form.collection_select :category_id, Category.all, :id, :title, prompt: true%>
Исправлено

2021-08-05 03:44 UTC, shudv2021 commented on app/controllers/questions_controller.rb
> +      render html: "<p>Question saved</p>".html_safe
исправил

2021-08-05 03:48 UTC, shudv2021 commented on config/routes.rb
> +  get '/questions/:id/del', to: 'questions#destroy'
убрал

2021-08-05 07:11 UTC, BubuntuClu requested changes

2021-08-05 07:11 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  # rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found
эту обработку надо вернуть в строй

2021-08-05 07:11 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +      render @test
что делает эта строчка? так работает?

2021-08-05 07:11 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  def parametrs
этот метод можно удалить уже

2021-08-05 07:11 UTC, BubuntuClu commented on app/views/layouts/_footer.html.erb
> +      <li><a href="https://github.com/shudv2021/TestGuru" target="_blank"> Исходники проекта.</a></li>
> Напишите хэлперы Для формирования ссылки на GitHub репозиторий: github_url(author, repo)

надо вынести это в хэлпер метод

2021-08-05 07:11 UTC, BubuntuClu commented on app/views/layouts/application.html.erb
> +  <footer>
этот код надо заменить на паршиал, который ты сделал, иначе это просто дублирование кода

2021-08-05 07:20 UTC, shudv2021 commented on db/migrate/20210802031931_add_test_default_creator.rb
> +      change_column_default(:tests, :user_id, 4)
исправлено. внесено seed

2021-08-05 07:21 UTC, shudv2021 commented on app/helpers/questions_helper.rb
> +    Test.find(params[:id]).title
исправлено

2021-08-05 07:22 UTC, shudv2021 commented on app/views/questions/new.html.erb
> +<h1>  Create new <%=question_header(@question)%> Question </h1>
исправлено

2021-08-05 08:29 UTC, shudv2021 commented on app/controllers/questions_controller.rb
> +  def parametrs
Удалил

2021-08-05 17:02 UTC, BubuntuClu requested changes

2021-08-05 17:02 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +      rescue_with_question_not_found
лучше вернуть просто на страницу этого вопроса и написать какой-нибудь текст

2021-08-05 17:02 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  def parametrs
нет, не удалил, он все еще в ПРе виден

2021-08-05 17:02 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    find_test
эту строку надо отсюда убрать

2021-08-05 17:02 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +      render :new
`render :edit`

2021-08-05 17:02 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +  def git_url
метод аргументом должен получать строку, внутри этого метода должна формироваться ссылка через хэлпер `link_to`.

2021-08-09 17:17 UTC, merged