lesson 9 attempt1
shudv2021/TestGuru pull request #9
Opened 2021-08-09 17:28 UTC by shudv2021

2021-08-09 18:02 UTC, BubuntuClu requested changes

2021-08-09 18:02 UTC, BubuntuClu commented on app/controllers/concerns/answers_controller.rb
> +    @answer = Answer.new(answer_params)
создавай ответ через объект вопроса через ассоциацию

2021-08-09 18:02 UTC, BubuntuClu commented on app/controllers/concerns/answers_controller.rb
> +    if @anwer.destroy
а если не удалился, тогда что?

2021-08-09 18:02 UTC, BubuntuClu commented on app/controllers/concerns/answers_controller.rb
> +      redirect_to @answer, notice: "Answer was seccessfuly create"
о5 успешно создан?)

2021-08-09 18:02 UTC, BubuntuClu commented on app/controllers/concerns/answers_controller.rb
> +    if @answer.save
какие изменения ты сохраняешь? тут другой метод нужен и параметры для него

2021-08-09 18:02 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    self.current_question = next_question
>Сделайте назначение следующего вопроса в модели TestPassage с помощью обратного вызова

этот пункт не сделал

2021-08-09 18:02 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    result? >= 85
85 сейчас магическое число. надо вынести в константу и обозвать понятно

2021-08-10 02:31 UTC, shudv2021 commented on app/controllers/concerns/answers_controller.rb
> +      redirect_to @answer, notice: "Answer was seccessfuly create"
исправил сообщение

2021-08-10 02:33 UTC, shudv2021 commented on app/controllers/concerns/answers_controller.rb
> +    if @answer.save
исправили

2021-08-10 02:37 UTC, shudv2021 commented on app/models/test_passage.rb
> +    result? >= 85
исправил

2021-08-10 04:10 UTC, shudv2021 commented on app/models/test_passage.rb
> +    self.current_question = next_question
исправил

2021-08-10 10:04 UTC, merged